services:
  postgres:
    container_name: "snaily-cad-postgres"
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    networks:
      - cad_web
    volumes:
      - ./.data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    container_name: "snaily-cad-api"
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "${PORT_API}:${PORT_API}"
    expose:
      - ${PORT_API}
    depends_on:
      - postgres
    networks:
      - cad_web
    restart: always

  client:
    container_name: "snaily-cad-client"
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    ports:
      - "${PORT_CLIENT}:${PORT_CLIENT}"
    expose:
      - ${PORT_CLIENT}
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - cad_web
    restart: always

networks:
  cad_web:
    external: true
